spring:
  application:
    name: bundle-plan-service
  datasource:
    url: jdbc:postgresql://postgres:5432/oar_bundle_plan
    username: oar_app
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8083

# Data Packaging Configuration  
distrib:
  packaging:
    maxpackagesize: 314572800
    maxfilecount: 50
    allowedurls: nist.gov|s3.amazonaws.com/nist-midas|s3.amazonaws.com/nist-srd|localhost
    allowedredirects: 7
  nerdm:
    baseurl: http://localhost:8090/id
