spring:
  application:
    name: data-bundle-service

server:
  port: 8084

# Data Packaging Configuration
distrib:
  packaging:
    maxpackagesize: 314572800
    maxfilecount: 50
    allowedurls: nist.gov|s3.amazonaws.com/nist-midas|s3.amazonaws.com/nist-srd|localhost
    allowedredirects: 7
  nerdm:
    baseurl: http://localhost:8090/id
