/**
 * This software was developed at the National Institute of Standards and Technology by employees of
 * the Federal Government in the course of their official duties. Pursuant to title 17 Section 105
 * of the United States Code this software is not subject to copyright protection and is in the
 * public domain. This is an experimental system. NIST assumes no responsibility whatsoever for its
 * use by other parties, and makes no guarantees, expressed or implied, about its quality,
 * reliability, or any other characteristic. We would appreciate acknowledgement if the software is
 * used. This software can be redistributed and/or modified freely provided that any derivative
 * works bear some notice that they are derived from it, and any modified versions bear some notice
 * that they have been modified.
 */
package gov.nist.oar.distrib.service.rpa;

import gov.nist.oar.common.cache.client.CacheManagerClient;
import gov.nist.oar.common.cache.exception.CacheClientException;
import gov.nist.oar.distrib.service.rpa.exceptions.RequestProcessingException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

/**
 * An implementation of the {@link RPADatasetCacher} interface that delegates to the
 * cache-mgmt service via the {@link CacheManagerClient}.
 * <p>
 * This implementation uses remote cache communication to ensure that RPA data caching
 * goes through the centralized cache-mgmt service, which maintains the cache inventory
 * in the shared PostgreSQL database. This is the correct microservices architecture
 * where all cache operations are centralized.
 * <p>
 * In the monolith, RPA caching used the same PDRCacheManager/BasicCache infrastructure
 * as regular caching, with role-based volume selection (ROLE_RESTRICTED_DATA) to direct
 * files to the appropriate volumes. This remote implementation maintains that same
 * behavior by delegating to cache-mgmt which has the same infrastructure.
 */
public class RemoteRPADatasetCacher implements RPADatasetCacher {

    private static final Logger LOGGER = LoggerFactory.getLogger(RemoteRPADatasetCacher.class);

    private final CacheManagerClient cacheManagerClient;

    /**
     * Create a new RemoteRPADatasetCacher that delegates to the cache-mgmt service.
     *
     * @param cacheManagerClient the client for communicating with cache-mgmt service
     */
    public RemoteRPADatasetCacher(CacheManagerClient cacheManagerClient) {
        this.cacheManagerClient = cacheManagerClient;
    }

    /**
     * Caches the dataset with the given ID using the remote cache-mgmt service.
     * <p>
     * This method calls the cache-mgmt service's RPA caching endpoint which:
     * <ul>
     *   <li>Generates a random ID with "rpa-" prefix</li>
     *   <li>Caches all files from the dataset with ROLE_RESTRICTED_DATA preference</li>
     *   <li>Returns the random ID that can be used to retrieve cached objects</li>
     * </ul>
     *
     * @param datasetId the ID of the dataset to cache
     * @return a random ID generated by the cache-mgmt service to represent the cached dataset
     * @throws RequestProcessingException if an error occurs while caching the dataset
     */
    @Override
    public String cache(String datasetId) throws RequestProcessingException {
        LOGGER.info("Caching dataset {} for RPA via remote cache-mgmt service", datasetId);

        try {
            // Call the cache-mgmt service to cache the dataset for RPA
            // Pass null for version to get the latest version (matching monolith behavior)
            Map<String, Object> result = cacheManagerClient.cacheDatasetForRPA(datasetId, null);

            String randomId = (String) result.get("randomId");
            Integer fileCount = (Integer) result.get("fileCount");

            LOGGER.info("Successfully cached dataset {} for RPA with randomId={}, fileCount={}",
                    datasetId, randomId, fileCount);

            return randomId;
        } catch (CacheClientException e) {
            LOGGER.error("Failed to cache dataset {} for RPA: {}", datasetId, e.getMessage());
            logCachingException(e);
            throw new RequestProcessingException("Failed to cache dataset for RPA: " + e.getMessage());
        } catch (Exception e) {
            LOGGER.error("Unexpected error while caching dataset {} for RPA: {}", datasetId, e.getMessage());
            logCachingException(e);
            throw new RequestProcessingException("Unexpected error caching dataset for RPA: " + e.getMessage());
        }
    }

    /**
     * Uncaches the dataset objects associated with the given random ID using the remote cache-mgmt service.
     *
     * @param randomId the random ID returned from the cache operation
     * @return true if at least one object was uncached, false otherwise
     * @throws RequestProcessingException if an error occurs while uncaching
     */
    @Override
    public boolean uncache(String randomId) {
        LOGGER.info("Uncaching RPA objects for randomId={} via remote cache-mgmt service", randomId);

        try {
            boolean result = cacheManagerClient.uncacheRPA(randomId);
            LOGGER.info("Uncache result for randomId={}: {}", randomId, result);
            return result;
        } catch (CacheClientException e) {
            LOGGER.error("Failed to uncache RPA objects for randomId={}: {}", randomId, e.getMessage());
            logCachingException(e);
            throw new RequestProcessingException("Failed to uncache RPA objects: " + e.getMessage());
        } catch (Exception e) {
            LOGGER.error("Unexpected error while uncaching RPA objects for randomId={}: {}", randomId, e.getMessage());
            logCachingException(e);
            throw new RequestProcessingException("Unexpected error uncaching RPA objects: " + e.getMessage());
        }
    }

    /**
     * Logs the specified exception to the error log, along with its stack trace.
     *
     * @param e the exception to log
     */
    private void logCachingException(Exception e) {
        StringBuilder sb = new StringBuilder();
        sb.append("Exception details: ").append(e.toString()).append("\n");
        for (StackTraceElement element : e.getStackTrace()) {
            sb.append("  at ").append(element.toString()).append("\n");
        }
        LOGGER.debug(sb.toString());
    }
}
